document.addEventListener('DOMContentLoaded', (event) => {
    const urlParams = new URLSearchParams(window.location.search);
    const term = urlParams.get('term');
    
    if (term) {
        document.getElementById('termName').innerText = term;
        document.getElementById('termDefinition').innerText = getDefinition(term);
        document.getElementById('termExamples').innerHTML = getExamples(term).map(ex => `<li>${ex}</li>`).join('');
        document.getElementById('relatedTerms').innerHTML = getRelatedTerms(term).map(rt => `<li><a href="term.html?term=${rt}">${rt}</a></li>`).join('');
        document.getElementById('additionalResources').innerHTML = getResources(term).map(res => `<li><a href="${res.url}">${res.title}</a></li>`).join('');
    }
});

function filterTerms() {
    let input = document.getElementById('searchBar');
    let filter = input.value.toLowerCase();
    let termList = document.getElementById('termList');
    let terms = termList.getElementsByTagName('li');
    let noResults = document.getElementById('noResults');
    let found = false;

    for (let i = 0; i < terms.length; i++) {
        let term = terms[i].getElementsByTagName('a')[0];
        let textValue = term.textContent || term.innerText;
        if (textValue.toLowerCase().indexOf(filter) > -1) {
            terms[i].style.display = '';
            found = true;
        } else {
            terms[i].style.display = 'none';
        }
    }
    if (!found) {
        noResults.style.display = 'block';
    } else {
        noResults.style.display = 'none';
    }
}


function getDefinition(term) {
    const definitions = {
        "Bribery": "The act of offering, giving, receiving, or soliciting something of value to influence the actions of an official or other person in a position of authority.",
        "Embezzlement": "The fraudulent appropriation of funds or property entrusted to one's care but actually owned by someone else.",
        "Fraud": "Wrongful or criminal deception intended to result in financial or personal gain.",
        "Graft": "The use of one's position or influence in government or business to obtain money or advantages in a dishonest way.",
        "Extortion": "The practice of obtaining something, especially money, through force or threats.",
        "Nepotism": "Favoritism granted to relatives or friends regardless of merit.",
        "Kickback": "A form of negotiated bribery in which a commission is paid to the bribe-taker in exchange for services rendered.",
        "Money Laundering": "The process of making large amounts of money generated by a criminal activity, such as drug trafficking or terrorist funding, appear to be earned legally.",
        "Cronyism": "The appointment of friends and associates to positions of authority without proper regard to their qualifications.",
        "Collusion": "Secret or illegal cooperation or conspiracy, especially in order to cheat or deceive others.",
        "Blackmail": "The act of threatening to reveal damaging information or take adverse action unless a demand is met, usually money.",
        "Patronage": "The power to control appointments to office or the right to privileges.",
        "Whistleblower": "A person who informs on a person or organization engaged in an illicit activity.",
        "Accountability": "The obligation of an individual or organization to account for its activities, accept responsibility for them, and disclose the results in a transparent manner.",
        "Transparency": "The quality of being easily seen through, recognized, or detected; in governance, it refers to the openness and clarity with which decisions are made.",
        "Integrity": "The quality of being honest and having strong moral principles.",
        "Misconduct": "Improper or illegal behavior by a person in a position of authority or trust.",
        "Conflict of Interest": "A situation in which a person is in a position to derive personal benefit from actions or decisions made in their official capacity.",
        "Impunity": "Exemption from punishment or freedom from the injurious consequences of an action.",
        "Fiduciary Duty": "A legal obligation of one party to act in the best interest of another. The obligated party is typically a fiduciary, that is, someone entrusted with the care of money or property."
    };
    return definitions[term] || "Definition not found.";
}

function getExamples(term) {
    const examples = {
       "Bribery": ["A company offering a government official money to secure a contract.", "A student bribing a teacher for better grades."],
            "Embezzlement": ["An employee transferring company funds into their personal account.", "A treasurer using organization's money for personal expenses."],
            "Fraud": ["A person using false information to obtain a loan.", "Insurance fraud by inflating claims."],
            "Graft": ["A politician receiving kickbacks for awarding contracts.", "A government official using their position to receive personal favors."],
            "Extortion": ["A criminal demanding money in exchange for protection.", "A hacker threatening to release sensitive data unless paid."],
            "Nepotism": ["A manager hiring a relative over more qualified candidates.", "Promotions given to family members within a company."],
            "Kickback": ["A supplier giving a percentage of contract value back to the buyer.", "Healthcare fraud involving referrals for money."],
            "Money Laundering": ["Using a legitimate business to disguise illegal income.", "Transferring funds through multiple accounts to obscure their origin."],
            "Cronyism": ["Appointing friends to government positions regardless of qualifications.", "Business leaders promoting associates over more competent employees."],
            "Collusion": ["Companies agreeing to fix prices.", "Bid rigging in government contracts."],
            "Blackmail": ["Threatening to reveal someone's affair unless they pay money.", "Using secret information to coerce someone into doing something."],
            "Patronage": ["A politician rewarding supporters with government jobs.", "Granting business favors in return for political support."],
            "Whistleblower": ["An employee exposing corporate fraud.", "A government worker revealing corruption within their department."],
            "Accountability": ["Officials being required to report on their actions and finances.", "Companies disclosing financial performance to shareholders."],
            "Transparency": ["Government publishing details of public spending.", "Organizations making their decision-making processes open to scrutiny."],
            "Integrity": ["A leader demonstrating honesty and strong moral principles.", "An employee refusing to participate in unethical practices."],
            "Misconduct": ["A police officer abusing their authority.", "A company executive engaging in unethical business practices."],
            "Conflict of Interest": ["A judge presiding over a case involving a family member.", "A politician voting on legislation that benefits their own business."],
            "Impunity": ["Officials not being held accountable for corrupt actions.", "Lack of legal consequences for corporate fraud."],
            "Fiduciary Duty": ["A financial advisor acting in the best interest of their client.", "A trustee managing a trust responsibly and ethically."]
    };
    return examples[term] || ["Examples not found."];
}

function getRelatedTerms(term) {
    const relatedTerms = {
        "Bribery": ["Corruption", "Extortion", "Kickback"],
        "Embezzlement": ["Fraud", "Graft", "Misconduct"],
        "Fraud": ["Deception", "Scam", "Misrepresentation"],
        "Graft": ["Corruption", "Bribery", "Embezzlement"],
        "Extortion": ["Blackmail", "Coercion", "Threat"],
        "Nepotism": ["Favoritism", "Cronyism", "Bias"],
        "Kickback": ["Bribery", "Graft", "Corruption"],
        "Money Laundering": ["Fraud", "Embezzlement", "Scam"],
        "Cronyism": ["Nepotism", "Favoritism", "Bias"],
        "Collusion": ["Conspiracy", "Secret Agreement", "Deception"],
        "Blackmail": ["Extortion", "Coercion", "Threat"],
        "Patronage": ["Support", "Sponsorship", "Endorsement"],
        "Whistleblower": ["Informer", "Revealer", "Exposer"],
        "Accountability": ["Responsibility", "Transparency", "Answerability"],
        "Transparency": ["Openness", "Clarity", "Accountability"],
        "Integrity": ["Honesty", "Principle", "Morality"],
        "Misconduct": ["Impropriety", "Malfeasance", "Wrongdoing"],
        "Conflict of Interest": ["Bias", "Partiality", "Compromise"],
        "Impunity": ["Exemption", "Freedom", "Immunity"],
        "Fiduciary Duty": ["Trust", "Responsibility", "Obligation"]

        // Add more related terms here
    };
    return relatedTerms[term] || [];
}

function getResources(term) {
    const resources = {
        "Bribery": [{title: "Article: How to Combat Bribery in Organizations", url: "resource1.html"}, {title: "Law: Anti-Bribery Act", url: "resource2.html"}],
            "Embezzlement": [{title: "Guide: Preventing Embezzlement in Your Business", url: "resource3.html"}, {title: "Case Study: Embezzlement Scandal", url: "resource4.html"}],
            "Fraud": [{title: "Report: Understanding Financial Fraud", url: "resource5.html"}, {title: "Article: Common Fraud Schemes", url: "resource6.html"}],
            "Graft": [{title: "Article: Political Graft and Its Impact", url: "resource7.html"}, {title: "Guide: Identifying Graft in Organizations", url: "resource8.html"}],
            "Extortion": [{title: "Guide: Dealing with Extortion Threats", url: "resource9.html"}, {title: "Law: Anti-Extortion Act", url: "resource10.html"}],
            "Nepotism": [{title: "Article: The Effects of Nepotism on Workplaces", url: "resource11.html"}, {title: "Guide: Addressing Nepotism in Business", url: "resource12.html"}],
            "Kickback": [{title: "Case Study: Kickback Scandal in Healthcare", url: "resource13.html"}, {title: "Guide: Preventing Kickbacks in Procurement", url: "resource14.html"}],
            "Money Laundering": [{title: "Report: Global Money Laundering Trends", url: "resource15.html"}, {title: "Guide: Anti-Money Laundering Strategies", url: "resource16.html"}],
            "Cronyism": [{title: "Article: The Dangers of Cronyism in Politics", url: "resource17.html"}, {title: "Guide: Promoting Meritocracy over Cronyism", url: "resource18.html"}],
            "Collusion": [{title: "Report: Corporate Collusion Cases", url: "resource19.html"}, {title: "Guide: Detecting Collusion in Markets", url: "resource20.html"}],
            "Blackmail": [{title: "Guide: Legal Remedies for Blackmail", url: "resource21.html"}, {title: "Case Study: Famous Blackmail Cases", url: "resource22.html"}],
            "Patronage": [{title: "Article: Political Patronage and its Consequences", url: "resource23.html"}, {title: "Guide: Reducing Patronage in Governance", url: "resource24.html"}],
            "Whistleblower": [{title: "Guide: Protecting Whistleblowers", url: "resource25.html"}, {title: "Article: Famous Whistleblowers in History", url: "resource26.html"}],
            "Accountability": [{title: "Report: Enhancing Accountability in Public Sector", url: "resource27.html"}, {title: "Guide: Accountability Measures in Business", url: "resource28.html"}],
            "Transparency": [{title: "Article: The Importance of Transparency", url: "resource29.html"}, {title: "Guide: Implementing Transparency Policies", url: "resource30.html"}],
            "Integrity": [{title: "Guide: Building Integrity in Leadership", url: "resource31.html"}, {title: "Article: Integrity in Business Practices", url: "resource32.html"}],
            "Misconduct": [{title: "Case Study: Corporate Misconduct Cases", url: "resource33.html"}, {title: "Guide: Addressing Misconduct in Organizations", url: "resource34.html"}],
            "Conflict of Interest": [{title: "Article: Managing Conflict of Interest", url: "resource35.html"}, {title: "Guide: Conflict of Interest Policies", url: "resource36.html"}],
            "Impunity": [{title: "Report: Impunity and Corruption", url: "resource37.html"}, {title: "Article: Addressing Impunity in Law", url: "resource38.html"}],
            "Fiduciary Duty": [{title: "Guide: Understanding Fiduciary Duty", url: "resource39.html"}, {title: "Article: Fiduciary Duty in Corporate Governance", url: "resource40.html"}]
    };
    return resources[term] || [];
}























